### ISSUE TITLE
Issue with abyssalcraft and abyssalcraft 1.7.10, crashes late into startup

### ISSUE THREAD

**Issue by Spearkirby** [Shinoow/AbyssalCraft-Integration#25] opened 2018-10-28 22:12 UTC
#### Description:

I'm using a modpack I assembled, just for personal playtime, after a long time of not playing modded 1.7.10. After fixing a slew of duplicate biome and enchantment ids, i've hit a brick wall with abyssalcraft integration
#### Crash report:
https://pastebin.com/j9r8CFmb
----

#### Affected versions:
- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- AbyssalCraft Integration:1.7.10-1.4.7
- AbyssalCraft: 1.7.10-1.9.1.3-FINAL

#### Latest log file for when the issue was present:
https://pastebin.com/TTfNKMQ6

**Comment by Shinoow** [comment] 2018-11-11 01:17
Duplicate of #14, read my reply there for more info.

**Closed by Shinoow** 2018-11-11 01:17 UTC
Labels: duplicate, wontfix
