### ISSUE TITLE
Bewitchment Conflict  

### ISSUE THREAD

**Issue by Alnarra** [Shinoow/AbyssalCraft-Integration#31] opened 2019-07-28 04:19 UTC
Crash on Open 

#### Crash report:

https://paste.dimdev.org/donoxalojo.mccrash

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge:14.23.5.2831
- AbyssalCraft Integration:1.8.1
- AbyssalCraft:1.9.10
- Bewitchment: 0.20.3

**Comment by Shinoow** [comment] 2019-07-28 11:24
Duplicate of #30. Fixed in 1.9.0

**Closed by Shinoow** 2019-07-28 11:24 UTC
Labels: duplicate
