### ISSUE TITLE
1.7.10 AC Integration Issues, java.lang.NullPointerException: Initializing game

### ISSUE THREAD

**Issue by Sudomatica** [Shinoow/AbyssalCraft-Integration#45] opened 2022-01-24 00:34 UTC
#### Description:

I am making a rather somewhat large modpack for 1.7.10, and the original Abyssalcraft will launch just fine by itself, but when I add in Integration, it crashes upon initialization. I tried disabling mods I don't use in the config file for AC Integration, but it didn't fix anything. There were a couple id issues I fixed between the Crash log and Latest log, but nothing changed. 

I did notice in the log it says:
[09:25:38] [Client thread/ERROR]: ItemStackToStackMap: AbyssalCraft Integration tried to insert an invalid value of [K: acintegration : Dreadium Dust V: acintegration : Dreadium Dust] into map 'furnace recipe map'

#### Crash report:

[pastebin/gist/etc link here if the bug results in a crash, leave line empty otherwise]

(https://pastebin.com/KHpRdMLT)

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- AbyssalCraft Integration: AbyssalCraft Integration-1.7.10-1.4.7
- AbyssalCraft: AbyssalCraft-1.7.10-1.9.1.3-FINAL

#### Latest log file for when the issue was present:

(https://pastebin.com/BsLP6iix)

**Comment by Shinoow** [comment] 2022-01-27 07:43
Duplicate of #14, read my reply there for more info.

**Closed as completed by Shinoow** 2022-01-27 07:43 UTC
Labels: duplicate, wontfix
